// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/Operational/DigitalTwinLayerOperationalService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace FSR.Aas.GRPC.Lib.V3.Services.Operational {
  public static partial class DigitalTwinLayerOperationalService
  {
    static readonly string __ServiceName = "FSR.Aas.GRPC.Lib.V3.Operational.DigitalTwinLayerOperationalService";

    static readonly grpc::Marshaller<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus> __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationStatus = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest> __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationInvokeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult> __Marshaller_FSR_Aas_GRPC_Lib_V3_OperationResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest> __Method_OpenOperationInvocationStream = new grpc::Method<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "OpenOperationInvocationStream",
        __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationStatus,
        __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationInvokeRequest);

    static readonly grpc::Method<global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> __Method_OpenOperationResultStream = new grpc::Method<global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "OpenOperationResultStream",
        __Marshaller_FSR_Aas_GRPC_Lib_V3_OperationResult,
        __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationRequest);

    static readonly grpc::Method<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> __Method_OpenExecutionStateStream = new grpc::Method<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "OpenExecutionStateStream",
        __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationStatus,
        __Marshaller_FSR_Aas_GRPC_Lib_V3_Operational_OperationRequest);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::FSR.Aas.GRPC.Lib.V3.Services.Operational.DigitalTwinLayerOperationalServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DigitalTwinLayerOperationalService</summary>
    [grpc::BindServiceMethod(typeof(DigitalTwinLayerOperationalService), "BindService")]
    public abstract partial class DigitalTwinLayerOperationalServiceBase
    {
      public virtual global::System.Threading.Tasks.Task OpenOperationInvocationStream(grpc::IAsyncStreamReader<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus> requestStream, grpc::IServerStreamWriter<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task OpenOperationResultStream(grpc::IAsyncStreamReader<global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult> requestStream, grpc::IServerStreamWriter<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task OpenExecutionStateStream(grpc::IAsyncStreamReader<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus> requestStream, grpc::IServerStreamWriter<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DigitalTwinLayerOperationalService</summary>
    public partial class DigitalTwinLayerOperationalServiceClient : grpc::ClientBase<DigitalTwinLayerOperationalServiceClient>
    {
      /// <summary>Creates a new client for DigitalTwinLayerOperationalService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DigitalTwinLayerOperationalServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DigitalTwinLayerOperationalService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DigitalTwinLayerOperationalServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DigitalTwinLayerOperationalServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DigitalTwinLayerOperationalServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest> OpenOperationInvocationStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenOperationInvocationStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest> OpenOperationInvocationStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_OpenOperationInvocationStream, null, options);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> OpenOperationResultStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenOperationResultStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> OpenOperationResultStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_OpenOperationResultStream, null, options);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> OpenExecutionStateStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenExecutionStateStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest> OpenExecutionStateStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_OpenExecutionStateStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DigitalTwinLayerOperationalServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DigitalTwinLayerOperationalServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DigitalTwinLayerOperationalServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_OpenOperationInvocationStream, serviceImpl.OpenOperationInvocationStream)
          .AddMethod(__Method_OpenOperationResultStream, serviceImpl.OpenOperationResultStream)
          .AddMethod(__Method_OpenExecutionStateStream, serviceImpl.OpenExecutionStateStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DigitalTwinLayerOperationalServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_OpenOperationInvocationStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationInvokeRequest>(serviceImpl.OpenOperationInvocationStream));
      serviceBinder.AddMethod(__Method_OpenOperationResultStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::FSR.Aas.GRPC.Lib.V3.Services.OperationResult, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest>(serviceImpl.OpenOperationResultStream));
      serviceBinder.AddMethod(__Method_OpenExecutionStateStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationStatus, global::FSR.Aas.GRPC.Lib.V3.Services.Operational.OperationRequest>(serviceImpl.OpenExecutionStateStream));
    }

  }
}
#endregion
