# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Services/Operational/DigitalTwinLayerOperationalService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Protos.AasModels import V3_pb2 as Protos_dot_AasModels_dot_V3__pb2
from Protos.AasApiModels import V3_pb2 as Protos_dot_AasApiModels_dot_V3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protos/Services/Operational/DigitalTwinLayerOperationalService.proto',
  package='FSR.Aas.GRPC.Lib.V3.Operational',
  syntax='proto3',
  serialized_options=_b('\252\002(FSR.Aas.GRPC.Lib.V3.Services.Operational'),
  serialized_pb=_b('\nDProtos/Services/Operational/DigitalTwinLayerOperationalService.proto\x12\x1f\x46SR.Aas.GRPC.Lib.V3.Operational\x1a\x19Protos/AasModels.V3.proto\x1a\x1cProtos/AasApiModels.V3.proto\"\xe7\x01\n\x16OperationInvokeRequest\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x41\n\x0einputVariables\x18\x02 \x03(\x0b\x32).FSR.Aas.GRPC.Lib.V3.OperationVariableDTO\x12\x41\n\x0einoutVariables\x18\x03 \x03(\x0b\x32).FSR.Aas.GRPC.Lib.V3.OperationVariableDTO\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0f\n\x07isAsync\x18\x05 \x01(\x08\x12\x10\n\x08handleId\x18\x06 \x01(\t\"%\n\x10OperationRequest\x12\x11\n\trequestId\x18\x01 \x01(\t\"a\n\x0fOperationStatus\x12\x11\n\trequestId\x18\x01 \x01(\t\x12;\n\x0e\x65xecutionState\x18\x02 \x01(\x0e\x32#.FSR.Aas.GRPC.Lib.V3.ExecutionState2\xb5\x03\n\"DigitalTwinLayerOperationalService\x12\x8e\x01\n\x1dOpenOperationInvocationStream\x12\x30.FSR.Aas.GRPC.Lib.V3.Operational.OperationStatus\x1a\x37.FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest(\x01\x30\x01\x12x\n\x19OpenOperationResultStream\x12$.FSR.Aas.GRPC.Lib.V3.OperationResult\x1a\x31.FSR.Aas.GRPC.Lib.V3.Operational.OperationRequest(\x01\x30\x01\x12\x83\x01\n\x18OpenExecutionStateStream\x12\x30.FSR.Aas.GRPC.Lib.V3.Operational.OperationStatus\x1a\x31.FSR.Aas.GRPC.Lib.V3.Operational.OperationRequest(\x01\x30\x01\x42+\xaa\x02(FSR.Aas.GRPC.Lib.V3.Services.Operationalb\x06proto3')
  ,
  dependencies=[Protos_dot_AasModels_dot_V3__pb2.DESCRIPTOR,Protos_dot_AasApiModels_dot_V3__pb2.DESCRIPTOR,])




_OPERATIONINVOKEREQUEST = _descriptor.Descriptor(
  name='OperationInvokeRequest',
  full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest.requestId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputVariables', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest.inputVariables', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inoutVariables', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest.inoutVariables', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isAsync', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest.isAsync', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handleId', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest.handleId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=394,
)


_OPERATIONREQUEST = _descriptor.Descriptor(
  name='OperationRequest',
  full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationRequest.requestId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=433,
)


_OPERATIONSTATUS = _descriptor.Descriptor(
  name='OperationStatus',
  full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationStatus.requestId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='executionState', full_name='FSR.Aas.GRPC.Lib.V3.Operational.OperationStatus.executionState', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=532,
)

_OPERATIONINVOKEREQUEST.fields_by_name['inputVariables'].message_type = Protos_dot_AasModels_dot_V3__pb2._OPERATIONVARIABLEDTO
_OPERATIONINVOKEREQUEST.fields_by_name['inoutVariables'].message_type = Protos_dot_AasModels_dot_V3__pb2._OPERATIONVARIABLEDTO
_OPERATIONSTATUS.fields_by_name['executionState'].enum_type = Protos_dot_AasApiModels_dot_V3__pb2._EXECUTIONSTATE
DESCRIPTOR.message_types_by_name['OperationInvokeRequest'] = _OPERATIONINVOKEREQUEST
DESCRIPTOR.message_types_by_name['OperationRequest'] = _OPERATIONREQUEST
DESCRIPTOR.message_types_by_name['OperationStatus'] = _OPERATIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperationInvokeRequest = _reflection.GeneratedProtocolMessageType('OperationInvokeRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONINVOKEREQUEST,
  '__module__' : 'Protos.Services.Operational.DigitalTwinLayerOperationalService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.Aas.GRPC.Lib.V3.Operational.OperationInvokeRequest)
  })
_sym_db.RegisterMessage(OperationInvokeRequest)

OperationRequest = _reflection.GeneratedProtocolMessageType('OperationRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONREQUEST,
  '__module__' : 'Protos.Services.Operational.DigitalTwinLayerOperationalService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.Aas.GRPC.Lib.V3.Operational.OperationRequest)
  })
_sym_db.RegisterMessage(OperationRequest)

OperationStatus = _reflection.GeneratedProtocolMessageType('OperationStatus', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONSTATUS,
  '__module__' : 'Protos.Services.Operational.DigitalTwinLayerOperationalService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.Aas.GRPC.Lib.V3.Operational.OperationStatus)
  })
_sym_db.RegisterMessage(OperationStatus)


DESCRIPTOR._options = None

_DIGITALTWINLAYEROPERATIONALSERVICE = _descriptor.ServiceDescriptor(
  name='DigitalTwinLayerOperationalService',
  full_name='FSR.Aas.GRPC.Lib.V3.Operational.DigitalTwinLayerOperationalService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=535,
  serialized_end=972,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenOperationInvocationStream',
    full_name='FSR.Aas.GRPC.Lib.V3.Operational.DigitalTwinLayerOperationalService.OpenOperationInvocationStream',
    index=0,
    containing_service=None,
    input_type=_OPERATIONSTATUS,
    output_type=_OPERATIONINVOKEREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OpenOperationResultStream',
    full_name='FSR.Aas.GRPC.Lib.V3.Operational.DigitalTwinLayerOperationalService.OpenOperationResultStream',
    index=1,
    containing_service=None,
    input_type=Protos_dot_AasApiModels_dot_V3__pb2._OPERATIONRESULT,
    output_type=_OPERATIONREQUEST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OpenExecutionStateStream',
    full_name='FSR.Aas.GRPC.Lib.V3.Operational.DigitalTwinLayerOperationalService.OpenExecutionStateStream',
    index=2,
    containing_service=None,
    input_type=_OPERATIONSTATUS,
    output_type=_OPERATIONREQUEST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIGITALTWINLAYEROPERATIONALSERVICE)

DESCRIPTOR.services_by_name['DigitalTwinLayerOperationalService'] = _DIGITALTWINLAYEROPERATIONALSERVICE

# @@protoc_insertion_point(module_scope)
