# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Services/Connection/DigitalTwinLayerConnectionService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Protos import DigitalTwinLayerModels_pb2 as Protos_dot_DigitalTwinLayerModels__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Protos/Services/Connection/DigitalTwinLayerConnectionService.proto',
  package='FSR.DigitalTwinLayer.GRPC.Lib',
  syntax='proto3',
  serialized_options=_b('\252\0021FSR.DigitalTwinLayer.GRPC.Lib.Services.Connection'),
  serialized_pb=_b('\nBProtos/Services/Connection/DigitalTwinLayerConnectionService.proto\x12\x1d\x46SR.DigitalTwinLayer.GRPC.Lib\x1a#Protos/DigitalTwinLayerModels.proto\"a\n\x0e\x43onnectRequest\x12\x41\n\x04type\x18\x01 \x01(\x0e\x32\x33.FSR.DigitalTwinLayer.GRPC.Lib.DigitalTwinLayerType\x12\x0c\n\x04info\x18\x02 \x01(\t\"D\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07layerId\x18\x03 \x01(\t\"l\n\x16\x41\x62ortConnectionRequest\x12\x0f\n\x07layerId\x18\x01 \x01(\t\x12\x41\n\x04type\x18\x02 \x01(\x0e\x32\x33.FSR.DigitalTwinLayer.GRPC.Lib.DigitalTwinLayerType\";\n\x17\x41\x62ortConnectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x90\x02\n!DigitalTwinLayerConnectionService\x12h\n\x07\x43onnect\x12-.FSR.DigitalTwinLayer.GRPC.Lib.ConnectRequest\x1a..FSR.DigitalTwinLayer.GRPC.Lib.ConnectResponse\x12\x80\x01\n\x0f\x41\x62ortConnection\x12\x35.FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionRequest\x1a\x36.FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionResponseB4\xaa\x02\x31\x46SR.DigitalTwinLayer.GRPC.Lib.Services.Connectionb\x06proto3')
  ,
  dependencies=[Protos_dot_DigitalTwinLayerModels__pb2.DESCRIPTOR,])




_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='FSR.DigitalTwinLayer.GRPC.Lib.ConnectRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='FSR.DigitalTwinLayer.GRPC.Lib.ConnectRequest.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=235,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FSR.DigitalTwinLayer.GRPC.Lib.ConnectResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='FSR.DigitalTwinLayer.GRPC.Lib.ConnectResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layerId', full_name='FSR.DigitalTwinLayer.GRPC.Lib.ConnectResponse.layerId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=305,
)


_ABORTCONNECTIONREQUEST = _descriptor.Descriptor(
  name='AbortConnectionRequest',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layerId', full_name='FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionRequest.layerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=415,
)


_ABORTCONNECTIONRESPONSE = _descriptor.Descriptor(
  name='AbortConnectionResponse',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=476,
)

_CONNECTREQUEST.fields_by_name['type'].enum_type = Protos_dot_DigitalTwinLayerModels__pb2._DIGITALTWINLAYERTYPE
_ABORTCONNECTIONREQUEST.fields_by_name['type'].enum_type = Protos_dot_DigitalTwinLayerModels__pb2._DIGITALTWINLAYERTYPE
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
DESCRIPTOR.message_types_by_name['AbortConnectionRequest'] = _ABORTCONNECTIONREQUEST
DESCRIPTOR.message_types_by_name['AbortConnectionResponse'] = _ABORTCONNECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'Protos.Services.Connection.DigitalTwinLayerConnectionService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'Protos.Services.Connection.DigitalTwinLayerConnectionService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)

AbortConnectionRequest = _reflection.GeneratedProtocolMessageType('AbortConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ABORTCONNECTIONREQUEST,
  '__module__' : 'Protos.Services.Connection.DigitalTwinLayerConnectionService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionRequest)
  })
_sym_db.RegisterMessage(AbortConnectionRequest)

AbortConnectionResponse = _reflection.GeneratedProtocolMessageType('AbortConnectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _ABORTCONNECTIONRESPONSE,
  '__module__' : 'Protos.Services.Connection.DigitalTwinLayerConnectionService_pb2'
  # @@protoc_insertion_point(class_scope:FSR.DigitalTwinLayer.GRPC.Lib.AbortConnectionResponse)
  })
_sym_db.RegisterMessage(AbortConnectionResponse)


DESCRIPTOR._options = None

_DIGITALTWINLAYERCONNECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='DigitalTwinLayerConnectionService',
  full_name='FSR.DigitalTwinLayer.GRPC.Lib.DigitalTwinLayerConnectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=479,
  serialized_end=751,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='FSR.DigitalTwinLayer.GRPC.Lib.DigitalTwinLayerConnectionService.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AbortConnection',
    full_name='FSR.DigitalTwinLayer.GRPC.Lib.DigitalTwinLayerConnectionService.AbortConnection',
    index=1,
    containing_service=None,
    input_type=_ABORTCONNECTIONREQUEST,
    output_type=_ABORTCONNECTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIGITALTWINLAYERCONNECTIONSERVICE)

DESCRIPTOR.services_by_name['DigitalTwinLayerConnectionService'] = _DIGITALTWINLAYERCONNECTIONSERVICE

# @@protoc_insertion_point(module_scope)
