// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/AasApiModels.V3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FSR.GRPC.Lib.V3.Services {

  /// <summary>Holder for reflection information generated from Protos/AasApiModels.V3.proto</summary>
  public static partial class AasApiModelsV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/AasApiModels.V3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AasApiModelsV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxQcm90b3MvQWFzQXBpTW9kZWxzLlYzLnByb3RvEg9GU1IuR1JQQy5MaWIu",
            "VjMiKwoZUGFnZWRSZXN1bHRQYWdpbmdNZXRhZGF0YRIOCgZjdXJzb3IYASAB",
            "KAkivAEKDk91dHB1dE1vZGlmaWVyEg4KBmN1cnNvchgBIAEoCRINCgVsaW1p",
            "dBgCIAEoBRIrCgVsZXZlbBgDIAEoDjIcLkZTUi5HUlBDLkxpYi5WMy5PdXRw",
            "dXRMZXZlbBIvCgdjb250ZW50GAQgASgOMh4uRlNSLkdSUEMuTGliLlYzLk91",
            "dHB1dENvbnRlbnQSLQoGZXh0ZW50GAUgASgOMh0uRlNSLkdSUEMuTGliLlYz",
            "Lk91dHB1dEV4dGVudCo7CgtPdXRwdXRMZXZlbBIVChFPVVRQVVRfTEVWRUxf",
            "REVFUBAAEhUKEU9VVFBVVF9MRVZFTF9DT1JFEAEqewoNT3V0cHV0Q29udGVu",
            "dBIZChVPVVRQVVRfQ09OVEVOVF9OT1JNQUwQABIYChRPVVRQVVRfQ09OVEVO",
            "VF9WQUxVRRABEhwKGE9VVFBVVF9DT05URU5UX1JFRkVSRU5DRRACEhcKE09V",
            "VFBVVF9DT05URU5UX1BBVEgQAypXCgxPdXRwdXRFeHRlbnQSJAogT1VUUFVU",
            "X0VYVEVOVF9XSVRIT1VUX0JMT0JfVkFMVUUQABIhCh1PVVRQVVRfRVhURU5U",
            "X1dJVEhfQkxPQl9WQUxVRRABQhuqAhhGU1IuR1JQQy5MaWIuVjMuU2Vydmlj",
            "ZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FSR.GRPC.Lib.V3.Services.OutputLevel), typeof(global::FSR.GRPC.Lib.V3.Services.OutputContent), typeof(global::FSR.GRPC.Lib.V3.Services.OutputExtent), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.PagedResultPagingMetadata), global::FSR.GRPC.Lib.V3.Services.PagedResultPagingMetadata.Parser, new[]{ "Cursor" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.OutputModifier), global::FSR.GRPC.Lib.V3.Services.OutputModifier.Parser, new[]{ "Cursor", "Limit", "Level", "Content", "Extent" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum OutputLevel {
    [pbr::OriginalName("OUTPUT_LEVEL_DEEP")] Deep = 0,
    [pbr::OriginalName("OUTPUT_LEVEL_CORE")] Core = 1,
  }

  public enum OutputContent {
    [pbr::OriginalName("OUTPUT_CONTENT_NORMAL")] Normal = 0,
    [pbr::OriginalName("OUTPUT_CONTENT_VALUE")] Value = 1,
    [pbr::OriginalName("OUTPUT_CONTENT_REFERENCE")] Reference = 2,
    [pbr::OriginalName("OUTPUT_CONTENT_PATH")] Path = 3,
  }

  public enum OutputExtent {
    [pbr::OriginalName("OUTPUT_EXTENT_WITHOUT_BLOB_VALUE")] WithoutBlobValue = 0,
    [pbr::OriginalName("OUTPUT_EXTENT_WITH_BLOB_VALUE")] WithBlobValue = 1,
  }

  #endregion

  #region Messages
  public sealed partial class PagedResultPagingMetadata : pb::IMessage<PagedResultPagingMetadata> {
    private static readonly pb::MessageParser<PagedResultPagingMetadata> _parser = new pb::MessageParser<PagedResultPagingMetadata>(() => new PagedResultPagingMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PagedResultPagingMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AasApiModelsV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PagedResultPagingMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PagedResultPagingMetadata(PagedResultPagingMetadata other) : this() {
      cursor_ = other.cursor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PagedResultPagingMetadata Clone() {
      return new PagedResultPagingMetadata(this);
    }

    /// <summary>Field number for the "cursor" field.</summary>
    public const int CursorFieldNumber = 1;
    private string cursor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cursor {
      get { return cursor_; }
      set {
        cursor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PagedResultPagingMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PagedResultPagingMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cursor != other.Cursor) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cursor.Length != 0) hash ^= Cursor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Cursor.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cursor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cursor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cursor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PagedResultPagingMetadata other) {
      if (other == null) {
        return;
      }
      if (other.Cursor.Length != 0) {
        Cursor = other.Cursor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cursor = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OutputModifier : pb::IMessage<OutputModifier> {
    private static readonly pb::MessageParser<OutputModifier> _parser = new pb::MessageParser<OutputModifier>(() => new OutputModifier());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutputModifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AasApiModelsV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputModifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputModifier(OutputModifier other) : this() {
      cursor_ = other.cursor_;
      limit_ = other.limit_;
      level_ = other.level_;
      content_ = other.content_;
      extent_ = other.extent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputModifier Clone() {
      return new OutputModifier(this);
    }

    /// <summary>Field number for the "cursor" field.</summary>
    public const int CursorFieldNumber = 1;
    private string cursor_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cursor {
      get { return cursor_; }
      set {
        cursor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "limit" field.</summary>
    public const int LimitFieldNumber = 2;
    private int limit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Limit {
      get { return limit_; }
      set {
        limit_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 3;
    private global::FSR.GRPC.Lib.V3.Services.OutputLevel level_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.Services.OutputLevel Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 4;
    private global::FSR.GRPC.Lib.V3.Services.OutputContent content_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.Services.OutputContent Content {
      get { return content_; }
      set {
        content_ = value;
      }
    }

    /// <summary>Field number for the "extent" field.</summary>
    public const int ExtentFieldNumber = 5;
    private global::FSR.GRPC.Lib.V3.Services.OutputExtent extent_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.Services.OutputExtent Extent {
      get { return extent_; }
      set {
        extent_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutputModifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutputModifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cursor != other.Cursor) return false;
      if (Limit != other.Limit) return false;
      if (Level != other.Level) return false;
      if (Content != other.Content) return false;
      if (Extent != other.Extent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cursor.Length != 0) hash ^= Cursor.GetHashCode();
      if (Limit != 0) hash ^= Limit.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Content != 0) hash ^= Content.GetHashCode();
      if (Extent != 0) hash ^= Extent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Cursor.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cursor);
      }
      if (Limit != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Limit);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Level);
      }
      if (Content != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Content);
      }
      if (Extent != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Extent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cursor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cursor);
      }
      if (Limit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Limit);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Level);
      }
      if (Content != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Content);
      }
      if (Extent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Extent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutputModifier other) {
      if (other == null) {
        return;
      }
      if (other.Cursor.Length != 0) {
        Cursor = other.Cursor;
      }
      if (other.Limit != 0) {
        Limit = other.Limit;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Content != 0) {
        Content = other.Content;
      }
      if (other.Extent != 0) {
        Extent = other.Extent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cursor = input.ReadString();
            break;
          }
          case 16: {
            Limit = input.ReadInt32();
            break;
          }
          case 24: {
            Level = (global::FSR.GRPC.Lib.V3.Services.OutputLevel) input.ReadEnum();
            break;
          }
          case 32: {
            Content = (global::FSR.GRPC.Lib.V3.Services.OutputContent) input.ReadEnum();
            break;
          }
          case 40: {
            Extent = (global::FSR.GRPC.Lib.V3.Services.OutputExtent) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
