// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/AdminShellRepositoryService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FSR.GRPC.V3.Services.AssetAdministrationShellRepository {

  /// <summary>Holder for reflection information generated from Protos/Services/AdminShellRepositoryService.proto</summary>
  public static partial class AdminShellRepositoryServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Services/AdminShellRepositoryService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdminShellRepositoryServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFQcm90b3MvU2VydmljZXMvQWRtaW5TaGVsbFJlcG9zaXRvcnlTZXJ2aWNl",
            "LnByb3RvEgtGU1IuR1JQQy5WMxoZUHJvdG9zL0Fhc01vZGVscy5WMy5wcm90",
            "bxocUHJvdG9zL0Fhc0FwaU1vZGVscy5WMy5wcm90byJgCilHZXRBbGxBc3Nl",
            "dEFkbWluaXN0cmF0aW9uU2hlbGxzUnBjUmVxdWVzdBIzCg5vdXRwdXRNb2Rp",
            "ZmllchgBIAEoCzIbLkZTUi5HUlBDLlYzLk91dHB1dE1vZGlmaWVyIu0BCipH",
            "ZXRBbGxBc3NldEFkbWluaXN0cmF0aW9uU2hlbGxzUnBjUmVzcG9uc2USEgoK",
            "c3RhdHVzQ29kZRgBIAEoBRI+Cg5wYWdpbmdNZXRhRGF0YRgCIAEoCzImLkZT",
            "Ui5HUlBDLlYzLlBhZ2VkUmVzdWx0UGFnaW5nTWV0YWRhdGESOwoHcGF5bG9h",
            "ZBgDIAMoCzIqLkZTUi5HUlBDLlYzLkFzc2V0QWRtaW5pc3RyYXRpb25TaGVs",
            "bE1vZGVsEi4KCXJlZmVyZW5jZRgEIAMoCzIbLkZTUi5HUlBDLlYzLlJlZmVy",
            "ZW5jZU1vZGVsImwKKUdldEFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbEJ5SWRS",
            "cGNSZXF1ZXN0EgoKAmlkGAEgASgJEjMKDm91dHB1dE1vZGlmaWVyGAIgASgL",
            "MhsuRlNSLkdSUEMuVjMuT3V0cHV0TW9kaWZpZXIirQEKKkdldEFzc2V0QWRt",
            "aW5pc3RyYXRpb25TaGVsbEJ5SWRScGNSZXNwb25zZRISCgpzdGF0dXNDb2Rl",
            "GAEgASgFEjsKB3BheWxvYWQYAiABKAsyKi5GU1IuR1JQQy5WMy5Bc3NldEFk",
            "bWluaXN0cmF0aW9uU2hlbGxNb2RlbBIuCglyZWZlcmVuY2UYAyABKAsyGy5G",
            "U1IuR1JQQy5WMy5SZWZlcmVuY2VNb2RlbCKNAQoyR2V0QWxsQXNzZXRBZG1p",
            "bmlzdHJhdGlvblNoZWxsc0J5QXNzZXRJZFJwY1JlcXVlc3QSCwoDa2V5GAEg",
            "ASgJEhUKDWtleUlkZW50aWZpZXIYAiABKAkSMwoOb3V0cHV0TW9kaWZpZXIY",
            "AyABKAsyGy5GU1IuR1JQQy5WMy5PdXRwdXRNb2RpZmllciL2AQozR2V0QWxs",
            "QXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsc0J5QXNzZXRJZFJwY1Jlc3BvbnNl",
            "EhIKCnN0YXR1c0NvZGUYASABKAUSPgoOcGFnaW5nTWV0YURhdGEYAiABKAsy",
            "Ji5GU1IuR1JQQy5WMy5QYWdlZFJlc3VsdFBhZ2luZ01ldGFkYXRhEjsKB3Bh",
            "eWxvYWQYAyADKAsyKi5GU1IuR1JQQy5WMy5Bc3NldEFkbWluaXN0cmF0aW9u",
            "U2hlbGxNb2RlbBIuCglyZWZlcmVuY2UYBCADKAsyGy5GU1IuR1JQQy5WMy5S",
            "ZWZlcmVuY2VNb2RlbCJ6CjJHZXRBbGxBc3NldEFkbWluaXN0cmF0aW9uU2hl",
            "bGxzQnlJZFNob3J0UnBjUmVxdWVzdBIPCgdpZFNob3J0GAEgASgJEjMKDm91",
            "dHB1dE1vZGlmaWVyGAIgASgLMhsuRlNSLkdSUEMuVjMuT3V0cHV0TW9kaWZp",
            "ZXIi9gEKM0dldEFsbEFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbHNCeUlkU2hv",
            "cnRScGNSZXNwb25zZRISCgpzdGF0dXNDb2RlGAEgASgFEj4KDnBhZ2luZ01l",
            "dGFEYXRhGAIgASgLMiYuRlNSLkdSUEMuVjMuUGFnZWRSZXN1bHRQYWdpbmdN",
            "ZXRhZGF0YRI7CgdwYXlsb2FkGAMgAygLMiouRlNSLkdSUEMuVjMuQXNzZXRB",
            "ZG1pbmlzdHJhdGlvblNoZWxsTW9kZWwSLgoJcmVmZXJlbmNlGAQgAygLMhsu",
            "RlNSLkdSUEMuVjMuUmVmZXJlbmNlTW9kZWwiYQomUG9zdEFzc2V0QWRtaW5p",
            "c3RyYXRpb25TaGVsbFJwY1JlcXVlc3QSNwoDYWFzGAEgASgLMiouRlNSLkdS",
            "UEMuVjMuQXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsTW9kZWwidgonUG9zdEFz",
            "c2V0QWRtaW5pc3RyYXRpb25TaGVsbFJwY1Jlc3BvbnNlEhIKCnN0YXR1c0Nv",
            "ZGUYASABKAUSNwoDYWFzGAIgASgLMiouRlNSLkdSUEMuVjMuQXNzZXRBZG1p",
            "bmlzdHJhdGlvblNoZWxsTW9kZWwiZAopUHV0QXNzZXRBZG1pbmlzdHJhdGlv",
            "blNoZWxsQnlJZFJwY1JlcXVlc3QSNwoDYWFzGAEgASgLMiouRlNSLkdSUEMu",
            "VjMuQXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsTW9kZWwieQoqUHV0QXNzZXRB",
            "ZG1pbmlzdHJhdGlvblNoZWxsQnlJZFJwY1Jlc3BvbnNlEhIKCnN0YXR1c0Nv",
            "ZGUYASABKAUSNwoDYWFzGAIgASgLMiouRlNSLkdSUEMuVjMuQXNzZXRBZG1p",
            "bmlzdHJhdGlvblNoZWxsTW9kZWwiOgosRGVsZXRlQXNzZXRBZG1pbmlzdHJh",
            "dGlvblNoZWxsQnlJZFJwY1JlcXVlc3QSCgoCaWQYASABKAkiQwotRGVsZXRl",
            "QXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsQnlJZFJwY1Jlc3BvbnNlEhIKCnN0",
            "YXR1c0NvZGUYASABKAUy9AgKKUFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbFJl",
            "cG9zaXRvcnlTZXJ2aWNlEpIBCh9HZXRBbGxBc3NldEFkbWluaXN0cmF0aW9u",
            "U2hlbGxzEjYuRlNSLkdSUEMuVjMuR2V0QWxsQXNzZXRBZG1pbmlzdHJhdGlv",
            "blNoZWxsc1JwY1JlcXVlc3QaNy5GU1IuR1JQQy5WMy5HZXRBbGxBc3NldEFk",
            "bWluaXN0cmF0aW9uU2hlbGxzUnBjUmVzcG9uc2USkgEKH0dldEFzc2V0QWRt",
            "aW5pc3RyYXRpb25TaGVsbEJ5SWQSNi5GU1IuR1JQQy5WMy5HZXRBc3NldEFk",
            "bWluaXN0cmF0aW9uU2hlbGxCeUlkUnBjUmVxdWVzdBo3LkZTUi5HUlBDLlYz",
            "LkdldEFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbEJ5SWRScGNSZXNwb25zZRKt",
            "AQooR2V0QWxsQXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsc0J5QXNzZXRJZBI/",
            "LkZTUi5HUlBDLlYzLkdldEFsbEFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbHNC",
            "eUFzc2V0SWRScGNSZXF1ZXN0GkAuRlNSLkdSUEMuVjMuR2V0QWxsQXNzZXRB",
            "ZG1pbmlzdHJhdGlvblNoZWxsc0J5QXNzZXRJZFJwY1Jlc3BvbnNlEq0BCihH",
            "ZXRBbGxBc3NldEFkbWluaXN0cmF0aW9uU2hlbGxzQnlJZFNob3J0Ej8uRlNS",
            "LkdSUEMuVjMuR2V0QWxsQXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsc0J5SWRT",
            "aG9ydFJwY1JlcXVlc3QaQC5GU1IuR1JQQy5WMy5HZXRBbGxBc3NldEFkbWlu",
            "aXN0cmF0aW9uU2hlbGxzQnlJZFNob3J0UnBjUmVzcG9uc2USiQEKHFBvc3RB",
            "c3NldEFkbWluaXN0cmF0aW9uU2hlbGwSMy5GU1IuR1JQQy5WMy5Qb3N0QXNz",
            "ZXRBZG1pbmlzdHJhdGlvblNoZWxsUnBjUmVxdWVzdBo0LkZTUi5HUlBDLlYz",
            "LlBvc3RBc3NldEFkbWluaXN0cmF0aW9uU2hlbGxScGNSZXNwb25zZRKSAQof",
            "UHV0QXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsQnlJZBI2LkZTUi5HUlBDLlYz",
            "LlB1dEFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbEJ5SWRScGNSZXF1ZXN0Gjcu",
            "RlNSLkdSUEMuVjMuUHV0QXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsQnlJZFJw",
            "Y1Jlc3BvbnNlEpsBCiJEZWxldGVBc3NldEFkbWluaXN0cmF0aW9uU2hlbGxC",
            "eUlkEjkuRlNSLkdSUEMuVjMuRGVsZXRlQXNzZXRBZG1pbmlzdHJhdGlvblNo",
            "ZWxsQnlJZFJwY1JlcXVlc3QaOi5GU1IuR1JQQy5WMy5EZWxldGVBc3NldEFk",
            "bWluaXN0cmF0aW9uU2hlbGxCeUlkUnBjUmVzcG9uc2VCOqoCN0ZTUi5HUlBD",
            "LlYzLlNlcnZpY2VzLkFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbFJlcG9zaXRv",
            "cnliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FSR.GRPC.V3.AasModelsV3Reflection.Descriptor, global::FSR.GRPC.V3.Services.AasApiModelsV3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsRpcRequest), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsRpcRequest.Parser, new[]{ "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsRpcResponse), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsRpcResponse.Parser, new[]{ "StatusCode", "PagingMetaData", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAssetAdministrationShellByIdRpcRequest), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAssetAdministrationShellByIdRpcRequest.Parser, new[]{ "Id", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAssetAdministrationShellByIdRpcResponse), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAssetAdministrationShellByIdRpcResponse.Parser, new[]{ "StatusCode", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByAssetIdRpcRequest), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByAssetIdRpcRequest.Parser, new[]{ "Key", "KeyIdentifier", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByAssetIdRpcResponse), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByAssetIdRpcResponse.Parser, new[]{ "StatusCode", "PagingMetaData", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByIdShortRpcRequest), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByIdShortRpcRequest.Parser, new[]{ "IdShort", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByIdShortRpcResponse), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.GetAllAssetAdministrationShellsByIdShortRpcResponse.Parser, new[]{ "StatusCode", "PagingMetaData", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PostAssetAdministrationShellRpcRequest), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PostAssetAdministrationShellRpcRequest.Parser, new[]{ "Aas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PostAssetAdministrationShellRpcResponse), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PostAssetAdministrationShellRpcResponse.Parser, new[]{ "StatusCode", "Aas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PutAssetAdministrationShellByIdRpcRequest), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PutAssetAdministrationShellByIdRpcRequest.Parser, new[]{ "Aas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PutAssetAdministrationShellByIdRpcResponse), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.PutAssetAdministrationShellByIdRpcResponse.Parser, new[]{ "StatusCode", "Aas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.DeleteAssetAdministrationShellByIdRpcRequest), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.DeleteAssetAdministrationShellByIdRpcRequest.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.DeleteAssetAdministrationShellByIdRpcResponse), global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.DeleteAssetAdministrationShellByIdRpcResponse.Parser, new[]{ "StatusCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetAllAssetAdministrationShellsRpcRequest : pb::IMessage<GetAllAssetAdministrationShellsRpcRequest> {
    private static readonly pb::MessageParser<GetAllAssetAdministrationShellsRpcRequest> _parser = new pb::MessageParser<GetAllAssetAdministrationShellsRpcRequest>(() => new GetAllAssetAdministrationShellsRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllAssetAdministrationShellsRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsRpcRequest(GetAllAssetAdministrationShellsRpcRequest other) : this() {
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsRpcRequest Clone() {
      return new GetAllAssetAdministrationShellsRpcRequest(this);
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 1;
    private global::FSR.GRPC.V3.Services.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.Services.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllAssetAdministrationShellsRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllAssetAdministrationShellsRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (outputModifier_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllAssetAdministrationShellsRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllAssetAdministrationShellsRpcResponse : pb::IMessage<GetAllAssetAdministrationShellsRpcResponse> {
    private static readonly pb::MessageParser<GetAllAssetAdministrationShellsRpcResponse> _parser = new pb::MessageParser<GetAllAssetAdministrationShellsRpcResponse>(() => new GetAllAssetAdministrationShellsRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllAssetAdministrationShellsRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsRpcResponse(GetAllAssetAdministrationShellsRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      pagingMetaData_ = other.pagingMetaData_ != null ? other.pagingMetaData_.Clone() : null;
      payload_ = other.payload_.Clone();
      reference_ = other.reference_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsRpcResponse Clone() {
      return new GetAllAssetAdministrationShellsRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "pagingMetaData" field.</summary>
    public const int PagingMetaDataFieldNumber = 2;
    private global::FSR.GRPC.V3.Services.PagedResultPagingMetadata pagingMetaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.Services.PagedResultPagingMetadata PagingMetaData {
      get { return pagingMetaData_; }
      set {
        pagingMetaData_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private static readonly pb::FieldCodec<global::FSR.GRPC.V3.AssetAdministrationShellModel> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(26, global::FSR.GRPC.V3.AssetAdministrationShellModel.Parser);
    private readonly pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel> payload_ = new pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 4;
    private static readonly pb::FieldCodec<global::FSR.GRPC.V3.ReferenceModel> _repeated_reference_codec
        = pb::FieldCodec.ForMessage(34, global::FSR.GRPC.V3.ReferenceModel.Parser);
    private readonly pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel> reference_ = new pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel> Reference {
      get { return reference_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllAssetAdministrationShellsRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllAssetAdministrationShellsRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(PagingMetaData, other.PagingMetaData)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if(!reference_.Equals(other.reference_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (pagingMetaData_ != null) hash ^= PagingMetaData.GetHashCode();
      hash ^= payload_.GetHashCode();
      hash ^= reference_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (pagingMetaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PagingMetaData);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      reference_.WriteTo(output, _repeated_reference_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (pagingMetaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PagingMetaData);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      size += reference_.CalculateSize(_repeated_reference_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllAssetAdministrationShellsRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.pagingMetaData_ != null) {
        if (pagingMetaData_ == null) {
          PagingMetaData = new global::FSR.GRPC.V3.Services.PagedResultPagingMetadata();
        }
        PagingMetaData.MergeFrom(other.PagingMetaData);
      }
      payload_.Add(other.payload_);
      reference_.Add(other.reference_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (pagingMetaData_ == null) {
              PagingMetaData = new global::FSR.GRPC.V3.Services.PagedResultPagingMetadata();
            }
            input.ReadMessage(PagingMetaData);
            break;
          }
          case 26: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 34: {
            reference_.AddEntriesFrom(input, _repeated_reference_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAssetAdministrationShellByIdRpcRequest : pb::IMessage<GetAssetAdministrationShellByIdRpcRequest> {
    private static readonly pb::MessageParser<GetAssetAdministrationShellByIdRpcRequest> _parser = new pb::MessageParser<GetAssetAdministrationShellByIdRpcRequest>(() => new GetAssetAdministrationShellByIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAssetAdministrationShellByIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellByIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellByIdRpcRequest(GetAssetAdministrationShellByIdRpcRequest other) : this() {
      id_ = other.id_;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellByIdRpcRequest Clone() {
      return new GetAssetAdministrationShellByIdRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 2;
    private global::FSR.GRPC.V3.Services.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.Services.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAssetAdministrationShellByIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAssetAdministrationShellByIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAssetAdministrationShellByIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAssetAdministrationShellByIdRpcResponse : pb::IMessage<GetAssetAdministrationShellByIdRpcResponse> {
    private static readonly pb::MessageParser<GetAssetAdministrationShellByIdRpcResponse> _parser = new pb::MessageParser<GetAssetAdministrationShellByIdRpcResponse>(() => new GetAssetAdministrationShellByIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAssetAdministrationShellByIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellByIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellByIdRpcResponse(GetAssetAdministrationShellByIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      payload_ = other.payload_ != null ? other.payload_.Clone() : null;
      reference_ = other.reference_ != null ? other.reference_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellByIdRpcResponse Clone() {
      return new GetAssetAdministrationShellByIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private global::FSR.GRPC.V3.AssetAdministrationShellModel payload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.AssetAdministrationShellModel Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 3;
    private global::FSR.GRPC.V3.ReferenceModel reference_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.ReferenceModel Reference {
      get { return reference_; }
      set {
        reference_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAssetAdministrationShellByIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAssetAdministrationShellByIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Payload, other.Payload)) return false;
      if (!object.Equals(Reference, other.Reference)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (payload_ != null) hash ^= Payload.GetHashCode();
      if (reference_ != null) hash ^= Reference.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (payload_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Payload);
      }
      if (reference_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Reference);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (reference_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reference);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAssetAdministrationShellByIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          Payload = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
        }
        Payload.MergeFrom(other.Payload);
      }
      if (other.reference_ != null) {
        if (reference_ == null) {
          Reference = new global::FSR.GRPC.V3.ReferenceModel();
        }
        Reference.MergeFrom(other.Reference);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (payload_ == null) {
              Payload = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
            }
            input.ReadMessage(Payload);
            break;
          }
          case 26: {
            if (reference_ == null) {
              Reference = new global::FSR.GRPC.V3.ReferenceModel();
            }
            input.ReadMessage(Reference);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllAssetAdministrationShellsByAssetIdRpcRequest : pb::IMessage<GetAllAssetAdministrationShellsByAssetIdRpcRequest> {
    private static readonly pb::MessageParser<GetAllAssetAdministrationShellsByAssetIdRpcRequest> _parser = new pb::MessageParser<GetAllAssetAdministrationShellsByAssetIdRpcRequest>(() => new GetAllAssetAdministrationShellsByAssetIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllAssetAdministrationShellsByAssetIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByAssetIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByAssetIdRpcRequest(GetAllAssetAdministrationShellsByAssetIdRpcRequest other) : this() {
      key_ = other.key_;
      keyIdentifier_ = other.keyIdentifier_;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByAssetIdRpcRequest Clone() {
      return new GetAllAssetAdministrationShellsByAssetIdRpcRequest(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "keyIdentifier" field.</summary>
    public const int KeyIdentifierFieldNumber = 2;
    private string keyIdentifier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string KeyIdentifier {
      get { return keyIdentifier_; }
      set {
        keyIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 3;
    private global::FSR.GRPC.V3.Services.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.Services.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllAssetAdministrationShellsByAssetIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllAssetAdministrationShellsByAssetIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (KeyIdentifier != other.KeyIdentifier) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (KeyIdentifier.Length != 0) hash ^= KeyIdentifier.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (KeyIdentifier.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(KeyIdentifier);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (KeyIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyIdentifier);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllAssetAdministrationShellsByAssetIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.KeyIdentifier.Length != 0) {
        KeyIdentifier = other.KeyIdentifier;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            KeyIdentifier = input.ReadString();
            break;
          }
          case 26: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllAssetAdministrationShellsByAssetIdRpcResponse : pb::IMessage<GetAllAssetAdministrationShellsByAssetIdRpcResponse> {
    private static readonly pb::MessageParser<GetAllAssetAdministrationShellsByAssetIdRpcResponse> _parser = new pb::MessageParser<GetAllAssetAdministrationShellsByAssetIdRpcResponse>(() => new GetAllAssetAdministrationShellsByAssetIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllAssetAdministrationShellsByAssetIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByAssetIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByAssetIdRpcResponse(GetAllAssetAdministrationShellsByAssetIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      pagingMetaData_ = other.pagingMetaData_ != null ? other.pagingMetaData_.Clone() : null;
      payload_ = other.payload_.Clone();
      reference_ = other.reference_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByAssetIdRpcResponse Clone() {
      return new GetAllAssetAdministrationShellsByAssetIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "pagingMetaData" field.</summary>
    public const int PagingMetaDataFieldNumber = 2;
    private global::FSR.GRPC.V3.Services.PagedResultPagingMetadata pagingMetaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.Services.PagedResultPagingMetadata PagingMetaData {
      get { return pagingMetaData_; }
      set {
        pagingMetaData_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private static readonly pb::FieldCodec<global::FSR.GRPC.V3.AssetAdministrationShellModel> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(26, global::FSR.GRPC.V3.AssetAdministrationShellModel.Parser);
    private readonly pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel> payload_ = new pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 4;
    private static readonly pb::FieldCodec<global::FSR.GRPC.V3.ReferenceModel> _repeated_reference_codec
        = pb::FieldCodec.ForMessage(34, global::FSR.GRPC.V3.ReferenceModel.Parser);
    private readonly pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel> reference_ = new pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel> Reference {
      get { return reference_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllAssetAdministrationShellsByAssetIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllAssetAdministrationShellsByAssetIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(PagingMetaData, other.PagingMetaData)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if(!reference_.Equals(other.reference_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (pagingMetaData_ != null) hash ^= PagingMetaData.GetHashCode();
      hash ^= payload_.GetHashCode();
      hash ^= reference_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (pagingMetaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PagingMetaData);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      reference_.WriteTo(output, _repeated_reference_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (pagingMetaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PagingMetaData);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      size += reference_.CalculateSize(_repeated_reference_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllAssetAdministrationShellsByAssetIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.pagingMetaData_ != null) {
        if (pagingMetaData_ == null) {
          PagingMetaData = new global::FSR.GRPC.V3.Services.PagedResultPagingMetadata();
        }
        PagingMetaData.MergeFrom(other.PagingMetaData);
      }
      payload_.Add(other.payload_);
      reference_.Add(other.reference_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (pagingMetaData_ == null) {
              PagingMetaData = new global::FSR.GRPC.V3.Services.PagedResultPagingMetadata();
            }
            input.ReadMessage(PagingMetaData);
            break;
          }
          case 26: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 34: {
            reference_.AddEntriesFrom(input, _repeated_reference_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllAssetAdministrationShellsByIdShortRpcRequest : pb::IMessage<GetAllAssetAdministrationShellsByIdShortRpcRequest> {
    private static readonly pb::MessageParser<GetAllAssetAdministrationShellsByIdShortRpcRequest> _parser = new pb::MessageParser<GetAllAssetAdministrationShellsByIdShortRpcRequest>(() => new GetAllAssetAdministrationShellsByIdShortRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllAssetAdministrationShellsByIdShortRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByIdShortRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByIdShortRpcRequest(GetAllAssetAdministrationShellsByIdShortRpcRequest other) : this() {
      idShort_ = other.idShort_;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByIdShortRpcRequest Clone() {
      return new GetAllAssetAdministrationShellsByIdShortRpcRequest(this);
    }

    /// <summary>Field number for the "idShort" field.</summary>
    public const int IdShortFieldNumber = 1;
    private string idShort_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdShort {
      get { return idShort_; }
      set {
        idShort_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 2;
    private global::FSR.GRPC.V3.Services.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.Services.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllAssetAdministrationShellsByIdShortRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllAssetAdministrationShellsByIdShortRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdShort != other.IdShort) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdShort.Length != 0) hash ^= IdShort.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdShort.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdShort);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdShort.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdShort);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllAssetAdministrationShellsByIdShortRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdShort.Length != 0) {
        IdShort = other.IdShort;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdShort = input.ReadString();
            break;
          }
          case 18: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.GRPC.V3.Services.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllAssetAdministrationShellsByIdShortRpcResponse : pb::IMessage<GetAllAssetAdministrationShellsByIdShortRpcResponse> {
    private static readonly pb::MessageParser<GetAllAssetAdministrationShellsByIdShortRpcResponse> _parser = new pb::MessageParser<GetAllAssetAdministrationShellsByIdShortRpcResponse>(() => new GetAllAssetAdministrationShellsByIdShortRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllAssetAdministrationShellsByIdShortRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByIdShortRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByIdShortRpcResponse(GetAllAssetAdministrationShellsByIdShortRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      pagingMetaData_ = other.pagingMetaData_ != null ? other.pagingMetaData_.Clone() : null;
      payload_ = other.payload_.Clone();
      reference_ = other.reference_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllAssetAdministrationShellsByIdShortRpcResponse Clone() {
      return new GetAllAssetAdministrationShellsByIdShortRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "pagingMetaData" field.</summary>
    public const int PagingMetaDataFieldNumber = 2;
    private global::FSR.GRPC.V3.Services.PagedResultPagingMetadata pagingMetaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.Services.PagedResultPagingMetadata PagingMetaData {
      get { return pagingMetaData_; }
      set {
        pagingMetaData_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private static readonly pb::FieldCodec<global::FSR.GRPC.V3.AssetAdministrationShellModel> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(26, global::FSR.GRPC.V3.AssetAdministrationShellModel.Parser);
    private readonly pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel> payload_ = new pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.GRPC.V3.AssetAdministrationShellModel> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 4;
    private static readonly pb::FieldCodec<global::FSR.GRPC.V3.ReferenceModel> _repeated_reference_codec
        = pb::FieldCodec.ForMessage(34, global::FSR.GRPC.V3.ReferenceModel.Parser);
    private readonly pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel> reference_ = new pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.GRPC.V3.ReferenceModel> Reference {
      get { return reference_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllAssetAdministrationShellsByIdShortRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllAssetAdministrationShellsByIdShortRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(PagingMetaData, other.PagingMetaData)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if(!reference_.Equals(other.reference_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (pagingMetaData_ != null) hash ^= PagingMetaData.GetHashCode();
      hash ^= payload_.GetHashCode();
      hash ^= reference_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (pagingMetaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PagingMetaData);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      reference_.WriteTo(output, _repeated_reference_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (pagingMetaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PagingMetaData);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      size += reference_.CalculateSize(_repeated_reference_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllAssetAdministrationShellsByIdShortRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.pagingMetaData_ != null) {
        if (pagingMetaData_ == null) {
          PagingMetaData = new global::FSR.GRPC.V3.Services.PagedResultPagingMetadata();
        }
        PagingMetaData.MergeFrom(other.PagingMetaData);
      }
      payload_.Add(other.payload_);
      reference_.Add(other.reference_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (pagingMetaData_ == null) {
              PagingMetaData = new global::FSR.GRPC.V3.Services.PagedResultPagingMetadata();
            }
            input.ReadMessage(PagingMetaData);
            break;
          }
          case 26: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 34: {
            reference_.AddEntriesFrom(input, _repeated_reference_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostAssetAdministrationShellRpcRequest : pb::IMessage<PostAssetAdministrationShellRpcRequest> {
    private static readonly pb::MessageParser<PostAssetAdministrationShellRpcRequest> _parser = new pb::MessageParser<PostAssetAdministrationShellRpcRequest>(() => new PostAssetAdministrationShellRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostAssetAdministrationShellRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAssetAdministrationShellRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAssetAdministrationShellRpcRequest(PostAssetAdministrationShellRpcRequest other) : this() {
      aas_ = other.aas_ != null ? other.aas_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAssetAdministrationShellRpcRequest Clone() {
      return new PostAssetAdministrationShellRpcRequest(this);
    }

    /// <summary>Field number for the "aas" field.</summary>
    public const int AasFieldNumber = 1;
    private global::FSR.GRPC.V3.AssetAdministrationShellModel aas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.AssetAdministrationShellModel Aas {
      get { return aas_; }
      set {
        aas_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostAssetAdministrationShellRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostAssetAdministrationShellRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Aas, other.Aas)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (aas_ != null) hash ^= Aas.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (aas_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Aas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (aas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Aas);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostAssetAdministrationShellRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.aas_ != null) {
        if (aas_ == null) {
          Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
        }
        Aas.MergeFrom(other.Aas);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (aas_ == null) {
              Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
            }
            input.ReadMessage(Aas);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostAssetAdministrationShellRpcResponse : pb::IMessage<PostAssetAdministrationShellRpcResponse> {
    private static readonly pb::MessageParser<PostAssetAdministrationShellRpcResponse> _parser = new pb::MessageParser<PostAssetAdministrationShellRpcResponse>(() => new PostAssetAdministrationShellRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostAssetAdministrationShellRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAssetAdministrationShellRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAssetAdministrationShellRpcResponse(PostAssetAdministrationShellRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      aas_ = other.aas_ != null ? other.aas_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostAssetAdministrationShellRpcResponse Clone() {
      return new PostAssetAdministrationShellRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "aas" field.</summary>
    public const int AasFieldNumber = 2;
    private global::FSR.GRPC.V3.AssetAdministrationShellModel aas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.AssetAdministrationShellModel Aas {
      get { return aas_; }
      set {
        aas_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostAssetAdministrationShellRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostAssetAdministrationShellRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Aas, other.Aas)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (aas_ != null) hash ^= Aas.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (aas_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Aas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (aas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Aas);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostAssetAdministrationShellRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.aas_ != null) {
        if (aas_ == null) {
          Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
        }
        Aas.MergeFrom(other.Aas);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (aas_ == null) {
              Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
            }
            input.ReadMessage(Aas);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutAssetAdministrationShellByIdRpcRequest : pb::IMessage<PutAssetAdministrationShellByIdRpcRequest> {
    private static readonly pb::MessageParser<PutAssetAdministrationShellByIdRpcRequest> _parser = new pb::MessageParser<PutAssetAdministrationShellByIdRpcRequest>(() => new PutAssetAdministrationShellByIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutAssetAdministrationShellByIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellByIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellByIdRpcRequest(PutAssetAdministrationShellByIdRpcRequest other) : this() {
      aas_ = other.aas_ != null ? other.aas_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellByIdRpcRequest Clone() {
      return new PutAssetAdministrationShellByIdRpcRequest(this);
    }

    /// <summary>Field number for the "aas" field.</summary>
    public const int AasFieldNumber = 1;
    private global::FSR.GRPC.V3.AssetAdministrationShellModel aas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.AssetAdministrationShellModel Aas {
      get { return aas_; }
      set {
        aas_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutAssetAdministrationShellByIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutAssetAdministrationShellByIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Aas, other.Aas)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (aas_ != null) hash ^= Aas.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (aas_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Aas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (aas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Aas);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutAssetAdministrationShellByIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.aas_ != null) {
        if (aas_ == null) {
          Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
        }
        Aas.MergeFrom(other.Aas);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (aas_ == null) {
              Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
            }
            input.ReadMessage(Aas);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutAssetAdministrationShellByIdRpcResponse : pb::IMessage<PutAssetAdministrationShellByIdRpcResponse> {
    private static readonly pb::MessageParser<PutAssetAdministrationShellByIdRpcResponse> _parser = new pb::MessageParser<PutAssetAdministrationShellByIdRpcResponse>(() => new PutAssetAdministrationShellByIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutAssetAdministrationShellByIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellByIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellByIdRpcResponse(PutAssetAdministrationShellByIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      aas_ = other.aas_ != null ? other.aas_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellByIdRpcResponse Clone() {
      return new PutAssetAdministrationShellByIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "aas" field.</summary>
    public const int AasFieldNumber = 2;
    private global::FSR.GRPC.V3.AssetAdministrationShellModel aas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.V3.AssetAdministrationShellModel Aas {
      get { return aas_; }
      set {
        aas_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutAssetAdministrationShellByIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutAssetAdministrationShellByIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Aas, other.Aas)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (aas_ != null) hash ^= Aas.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (aas_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Aas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (aas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Aas);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutAssetAdministrationShellByIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.aas_ != null) {
        if (aas_ == null) {
          Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
        }
        Aas.MergeFrom(other.Aas);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (aas_ == null) {
              Aas = new global::FSR.GRPC.V3.AssetAdministrationShellModel();
            }
            input.ReadMessage(Aas);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteAssetAdministrationShellByIdRpcRequest : pb::IMessage<DeleteAssetAdministrationShellByIdRpcRequest> {
    private static readonly pb::MessageParser<DeleteAssetAdministrationShellByIdRpcRequest> _parser = new pb::MessageParser<DeleteAssetAdministrationShellByIdRpcRequest>(() => new DeleteAssetAdministrationShellByIdRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteAssetAdministrationShellByIdRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteAssetAdministrationShellByIdRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteAssetAdministrationShellByIdRpcRequest(DeleteAssetAdministrationShellByIdRpcRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteAssetAdministrationShellByIdRpcRequest Clone() {
      return new DeleteAssetAdministrationShellByIdRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteAssetAdministrationShellByIdRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteAssetAdministrationShellByIdRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteAssetAdministrationShellByIdRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteAssetAdministrationShellByIdRpcResponse : pb::IMessage<DeleteAssetAdministrationShellByIdRpcResponse> {
    private static readonly pb::MessageParser<DeleteAssetAdministrationShellByIdRpcResponse> _parser = new pb::MessageParser<DeleteAssetAdministrationShellByIdRpcResponse>(() => new DeleteAssetAdministrationShellByIdRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteAssetAdministrationShellByIdRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.V3.Services.AssetAdministrationShellRepository.AdminShellRepositoryServiceReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteAssetAdministrationShellByIdRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteAssetAdministrationShellByIdRpcResponse(DeleteAssetAdministrationShellByIdRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteAssetAdministrationShellByIdRpcResponse Clone() {
      return new DeleteAssetAdministrationShellByIdRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteAssetAdministrationShellByIdRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteAssetAdministrationShellByIdRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteAssetAdministrationShellByIdRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
