// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/AssetAdministrationShellService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService {

  /// <summary>Holder for reflection information generated from Protos/Services/AssetAdministrationShellService.proto</summary>
  public static partial class AssetAdministrationShellServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/Services/AssetAdministrationShellService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AssetAdministrationShellServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVQcm90b3MvU2VydmljZXMvQXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsU2Vy",
            "dmljZS5wcm90bxIPRlNSLkdSUEMuTGliLlYzGhlQcm90b3MvQWFzTW9kZWxz",
            "LlYzLnByb3RvGhxQcm90b3MvQWFzQXBpTW9kZWxzLlYzLnByb3RvImwKJUdl",
            "dEFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbFJwY1JlcXVlc3QSCgoCaWQYASAB",
            "KAkSNwoOb3V0cHV0TW9kaWZpZXIYAiABKAsyHy5GU1IuR1JQQy5MaWIuVjMu",
            "T3V0cHV0TW9kaWZpZXIirQEKJkdldEFzc2V0QWRtaW5pc3RyYXRpb25TaGVs",
            "bFJwY1Jlc3BvbnNlEhIKCnN0YXR1c0NvZGUYASABKAUSPQoHcGF5bG9hZBgC",
            "IAEoCzIsLkZTUi5HUlBDLkxpYi5WMy5Bc3NldEFkbWluaXN0cmF0aW9uU2hl",
            "bGxEVE8SMAoJcmVmZXJlbmNlGAMgASgLMh0uRlNSLkdSUEMuTGliLlYzLlJl",
            "ZmVyZW5jZURUTyJuCiVQdXRBc3NldEFkbWluaXN0cmF0aW9uU2hlbGxScGNS",
            "ZXF1ZXN0EgoKAmlkGAEgASgJEjkKA2FhcxgCIAEoCzIsLkZTUi5HUlBDLkxp",
            "Yi5WMy5Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGxEVE8idwomUHV0QXNzZXRB",
            "ZG1pbmlzdHJhdGlvblNoZWxsUnBjUmVzcG9uc2USEgoKc3RhdHVzQ29kZRgB",
            "IAEoBRI5CgNhYXMYAiABKAsyLC5GU1IuR1JQQy5MaWIuVjMuQXNzZXRBZG1p",
            "bmlzdHJhdGlvblNoZWxsRFRPImkKIkdldEFsbFN1Ym1vZGVsUmVmZXJlbmNl",
            "c1JwY1JlcXVlc3QSCgoCaWQYASABKAkSNwoOb3V0cHV0TW9kaWZpZXIYAiAB",
            "KAsyHy5GU1IuR1JQQy5MaWIuVjMuT3V0cHV0TW9kaWZpZXIirQEKI0dldEFs",
            "bFN1Ym1vZGVsUmVmZXJlbmNlc1JwY1Jlc3BvbnNlEhIKCnN0YXR1c0NvZGUY",
            "ASABKAUSQgoOcGFnaW5nTWV0YURhdGEYAiABKAsyKi5GU1IuR1JQQy5MaWIu",
            "VjMuUGFnZWRSZXN1bHRQYWdpbmdNZXRhZGF0YRIuCgdwYXlsb2FkGAMgAygL",
            "Mh0uRlNSLkdSUEMuTGliLlYzLlJlZmVyZW5jZURUTyJhCh9Qb3N0U3VibW9k",
            "ZWxSZWZlcmVuY2VScGNSZXF1ZXN0EgoKAmlkGAEgASgJEjIKC3N1Ym1vZGVs",
            "UmVmGAIgASgLMh0uRlNSLkdSUEMuTGliLlYzLlJlZmVyZW5jZURUTyJqCiBQ",
            "b3N0U3VibW9kZWxSZWZlcmVuY2VScGNSZXNwb25zZRISCgpzdGF0dXNDb2Rl",
            "GAEgASgFEjIKC3N1Ym1vZGVsUmVmGAIgASgLMh0uRlNSLkdSUEMuTGliLlYz",
            "LlJlZmVyZW5jZURUTyJDCiFEZWxldGVTdWJtb2RlbFJlZmVyZW5jZVJwY1Jl",
            "cXVlc3QSCgoCaWQYASABKAkSEgoKc3VibW9kZWxJZBgCIAEoCSI4CiJEZWxl",
            "dGVTdWJtb2RlbFJlZmVyZW5jZVJwY1Jlc3BvbnNlEhIKCnN0YXR1c0NvZGUY",
            "ASABKAUiKwodR2V0QXNzZXRJbmZvcm1hdGlvblJwY1JlcXVlc3QSCgoCaWQY",
            "ASABKAkidAoeR2V0QXNzZXRJbmZvcm1hdGlvblJwY1Jlc3BvbnNlEhIKCnN0",
            "YXR1c0NvZGUYASABKAUSPgoQYXNzZXRJbmZvcm1hdGlvbhgCIAEoCzIkLkZT",
            "Ui5HUlBDLkxpYi5WMy5Bc3NldEluZm9ybWF0aW9uRFRPImsKHVB1dEFzc2V0",
            "SW5mb3JtYXRpb25ScGNSZXF1ZXN0EgoKAmlkGAEgASgJEj4KEGFzc2V0SW5m",
            "b3JtYXRpb24YAiABKAsyJC5GU1IuR1JQQy5MaWIuVjMuQXNzZXRJbmZvcm1h",
            "dGlvbkRUTyJ0Ch5QdXRBc3NldEluZm9ybWF0aW9uUnBjUmVzcG9uc2USEgoK",
            "c3RhdHVzQ29kZRgBIAEoBRI+ChBhc3NldEluZm9ybWF0aW9uGAIgASgLMiQu",
            "RlNSLkdSUEMuTGliLlYzLkFzc2V0SW5mb3JtYXRpb25EVE8yvgcKH0Fzc2V0",
            "QWRtaW5pc3RyYXRpb25TaGVsbFNlcnZpY2USjgEKG0dldEFzc2V0QWRtaW5p",
            "c3RyYXRpb25TaGVsbBI2LkZTUi5HUlBDLkxpYi5WMy5HZXRBc3NldEFkbWlu",
            "aXN0cmF0aW9uU2hlbGxScGNSZXF1ZXN0GjcuRlNSLkdSUEMuTGliLlYzLkdl",
            "dEFzc2V0QWRtaW5pc3RyYXRpb25TaGVsbFJwY1Jlc3BvbnNlEo4BChtQdXRB",
            "c3NldEFkbWluaXN0cmF0aW9uU2hlbGwSNi5GU1IuR1JQQy5MaWIuVjMuUHV0",
            "QXNzZXRBZG1pbmlzdHJhdGlvblNoZWxsUnBjUmVxdWVzdBo3LkZTUi5HUlBD",
            "LkxpYi5WMy5QdXRBc3NldEFkbWluaXN0cmF0aW9uU2hlbGxScGNSZXNwb25z",
            "ZRKFAQoYR2V0QWxsU3VibW9kZWxSZWZlcmVuY2VzEjMuRlNSLkdSUEMuTGli",
            "LlYzLkdldEFsbFN1Ym1vZGVsUmVmZXJlbmNlc1JwY1JlcXVlc3QaNC5GU1Iu",
            "R1JQQy5MaWIuVjMuR2V0QWxsU3VibW9kZWxSZWZlcmVuY2VzUnBjUmVzcG9u",
            "c2USfAoVUG9zdFN1Ym1vZGVsUmVmZXJlbmNlEjAuRlNSLkdSUEMuTGliLlYz",
            "LlBvc3RTdWJtb2RlbFJlZmVyZW5jZVJwY1JlcXVlc3QaMS5GU1IuR1JQQy5M",
            "aWIuVjMuUG9zdFN1Ym1vZGVsUmVmZXJlbmNlUnBjUmVzcG9uc2USggEKF0Rl",
            "bGV0ZVN1Ym1vZGVsUmVmZXJlbmNlEjIuRlNSLkdSUEMuTGliLlYzLkRlbGV0",
            "ZVN1Ym1vZGVsUmVmZXJlbmNlUnBjUmVxdWVzdBozLkZTUi5HUlBDLkxpYi5W",
            "My5EZWxldGVTdWJtb2RlbFJlZmVyZW5jZVJwY1Jlc3BvbnNlEnYKE0dldEFz",
            "c2V0SW5mb3JtYXRpb24SLi5GU1IuR1JQQy5MaWIuVjMuR2V0QXNzZXRJbmZv",
            "cm1hdGlvblJwY1JlcXVlc3QaLy5GU1IuR1JQQy5MaWIuVjMuR2V0QXNzZXRJ",
            "bmZvcm1hdGlvblJwY1Jlc3BvbnNlEnYKE1B1dEFzc2V0SW5mb3JtYXRpb24S",
            "Li5GU1IuR1JQQy5MaWIuVjMuUHV0QXNzZXRJbmZvcm1hdGlvblJwY1JlcXVl",
            "c3QaLy5GU1IuR1JQQy5MaWIuVjMuUHV0QXNzZXRJbmZvcm1hdGlvblJwY1Jl",
            "c3BvbnNlQjuqAjhGU1IuR1JQQy5MaWIuVjMuU2VydmljZXMuQXNzZXRBZG1p",
            "bmlzdHJhdGlvblNoZWxsU2VydmljZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::FSR.GRPC.Lib.V3.AasModelsV3Reflection.Descriptor, global::FSR.GRPC.Lib.V3.Services.AasApiModelsV3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetAdministrationShellRpcRequest), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetAdministrationShellRpcRequest.Parser, new[]{ "Id", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetAdministrationShellRpcResponse), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetAdministrationShellRpcResponse.Parser, new[]{ "StatusCode", "Payload", "Reference" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetAdministrationShellRpcRequest), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetAdministrationShellRpcRequest.Parser, new[]{ "Id", "Aas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetAdministrationShellRpcResponse), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetAdministrationShellRpcResponse.Parser, new[]{ "StatusCode", "Aas" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAllSubmodelReferencesRpcRequest), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAllSubmodelReferencesRpcRequest.Parser, new[]{ "Id", "OutputModifier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAllSubmodelReferencesRpcResponse), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAllSubmodelReferencesRpcResponse.Parser, new[]{ "StatusCode", "PagingMetaData", "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PostSubmodelReferenceRpcRequest), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PostSubmodelReferenceRpcRequest.Parser, new[]{ "Id", "SubmodelRef" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PostSubmodelReferenceRpcResponse), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PostSubmodelReferenceRpcResponse.Parser, new[]{ "StatusCode", "SubmodelRef" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.DeleteSubmodelReferenceRpcRequest), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.DeleteSubmodelReferenceRpcRequest.Parser, new[]{ "Id", "SubmodelId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.DeleteSubmodelReferenceRpcResponse), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.DeleteSubmodelReferenceRpcResponse.Parser, new[]{ "StatusCode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetInformationRpcRequest), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetInformationRpcRequest.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetInformationRpcResponse), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.GetAssetInformationRpcResponse.Parser, new[]{ "StatusCode", "AssetInformation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetInformationRpcRequest), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetInformationRpcRequest.Parser, new[]{ "Id", "AssetInformation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetInformationRpcResponse), global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.PutAssetInformationRpcResponse.Parser, new[]{ "StatusCode", "AssetInformation" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetAssetAdministrationShellRpcRequest : pb::IMessage<GetAssetAdministrationShellRpcRequest> {
    private static readonly pb::MessageParser<GetAssetAdministrationShellRpcRequest> _parser = new pb::MessageParser<GetAssetAdministrationShellRpcRequest>(() => new GetAssetAdministrationShellRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAssetAdministrationShellRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellRpcRequest(GetAssetAdministrationShellRpcRequest other) : this() {
      id_ = other.id_;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellRpcRequest Clone() {
      return new GetAssetAdministrationShellRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.Services.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.Services.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAssetAdministrationShellRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAssetAdministrationShellRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAssetAdministrationShellRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.GRPC.Lib.V3.Services.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.GRPC.Lib.V3.Services.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAssetAdministrationShellRpcResponse : pb::IMessage<GetAssetAdministrationShellRpcResponse> {
    private static readonly pb::MessageParser<GetAssetAdministrationShellRpcResponse> _parser = new pb::MessageParser<GetAssetAdministrationShellRpcResponse>(() => new GetAssetAdministrationShellRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAssetAdministrationShellRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellRpcResponse(GetAssetAdministrationShellRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      payload_ = other.payload_ != null ? other.payload_.Clone() : null;
      reference_ = other.reference_ != null ? other.reference_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetAdministrationShellRpcResponse Clone() {
      return new GetAssetAdministrationShellRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO payload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 3;
    private global::FSR.GRPC.Lib.V3.ReferenceDTO reference_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.ReferenceDTO Reference {
      get { return reference_; }
      set {
        reference_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAssetAdministrationShellRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAssetAdministrationShellRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Payload, other.Payload)) return false;
      if (!object.Equals(Reference, other.Reference)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (payload_ != null) hash ^= Payload.GetHashCode();
      if (reference_ != null) hash ^= Reference.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (payload_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Payload);
      }
      if (reference_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Reference);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (reference_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reference);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAssetAdministrationShellRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          Payload = new global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO();
        }
        Payload.MergeFrom(other.Payload);
      }
      if (other.reference_ != null) {
        if (reference_ == null) {
          Reference = new global::FSR.GRPC.Lib.V3.ReferenceDTO();
        }
        Reference.MergeFrom(other.Reference);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (payload_ == null) {
              Payload = new global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO();
            }
            input.ReadMessage(Payload);
            break;
          }
          case 26: {
            if (reference_ == null) {
              Reference = new global::FSR.GRPC.Lib.V3.ReferenceDTO();
            }
            input.ReadMessage(Reference);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutAssetAdministrationShellRpcRequest : pb::IMessage<PutAssetAdministrationShellRpcRequest> {
    private static readonly pb::MessageParser<PutAssetAdministrationShellRpcRequest> _parser = new pb::MessageParser<PutAssetAdministrationShellRpcRequest>(() => new PutAssetAdministrationShellRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutAssetAdministrationShellRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellRpcRequest(PutAssetAdministrationShellRpcRequest other) : this() {
      id_ = other.id_;
      aas_ = other.aas_ != null ? other.aas_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellRpcRequest Clone() {
      return new PutAssetAdministrationShellRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "aas" field.</summary>
    public const int AasFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO aas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO Aas {
      get { return aas_; }
      set {
        aas_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutAssetAdministrationShellRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutAssetAdministrationShellRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Aas, other.Aas)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (aas_ != null) hash ^= Aas.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (aas_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Aas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (aas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Aas);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutAssetAdministrationShellRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.aas_ != null) {
        if (aas_ == null) {
          Aas = new global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO();
        }
        Aas.MergeFrom(other.Aas);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (aas_ == null) {
              Aas = new global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO();
            }
            input.ReadMessage(Aas);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutAssetAdministrationShellRpcResponse : pb::IMessage<PutAssetAdministrationShellRpcResponse> {
    private static readonly pb::MessageParser<PutAssetAdministrationShellRpcResponse> _parser = new pb::MessageParser<PutAssetAdministrationShellRpcResponse>(() => new PutAssetAdministrationShellRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutAssetAdministrationShellRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellRpcResponse(PutAssetAdministrationShellRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      aas_ = other.aas_ != null ? other.aas_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetAdministrationShellRpcResponse Clone() {
      return new PutAssetAdministrationShellRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "aas" field.</summary>
    public const int AasFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO aas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO Aas {
      get { return aas_; }
      set {
        aas_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutAssetAdministrationShellRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutAssetAdministrationShellRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(Aas, other.Aas)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (aas_ != null) hash ^= Aas.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (aas_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Aas);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (aas_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Aas);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutAssetAdministrationShellRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.aas_ != null) {
        if (aas_ == null) {
          Aas = new global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO();
        }
        Aas.MergeFrom(other.Aas);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (aas_ == null) {
              Aas = new global::FSR.GRPC.Lib.V3.AssetAdministrationShellDTO();
            }
            input.ReadMessage(Aas);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllSubmodelReferencesRpcRequest : pb::IMessage<GetAllSubmodelReferencesRpcRequest> {
    private static readonly pb::MessageParser<GetAllSubmodelReferencesRpcRequest> _parser = new pb::MessageParser<GetAllSubmodelReferencesRpcRequest>(() => new GetAllSubmodelReferencesRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelReferencesRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelReferencesRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelReferencesRpcRequest(GetAllSubmodelReferencesRpcRequest other) : this() {
      id_ = other.id_;
      outputModifier_ = other.outputModifier_ != null ? other.outputModifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelReferencesRpcRequest Clone() {
      return new GetAllSubmodelReferencesRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "outputModifier" field.</summary>
    public const int OutputModifierFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.Services.OutputModifier outputModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.Services.OutputModifier OutputModifier {
      get { return outputModifier_; }
      set {
        outputModifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelReferencesRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelReferencesRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(OutputModifier, other.OutputModifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (outputModifier_ != null) hash ^= OutputModifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (outputModifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OutputModifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (outputModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OutputModifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelReferencesRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.outputModifier_ != null) {
        if (outputModifier_ == null) {
          OutputModifier = new global::FSR.GRPC.Lib.V3.Services.OutputModifier();
        }
        OutputModifier.MergeFrom(other.OutputModifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (outputModifier_ == null) {
              OutputModifier = new global::FSR.GRPC.Lib.V3.Services.OutputModifier();
            }
            input.ReadMessage(OutputModifier);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllSubmodelReferencesRpcResponse : pb::IMessage<GetAllSubmodelReferencesRpcResponse> {
    private static readonly pb::MessageParser<GetAllSubmodelReferencesRpcResponse> _parser = new pb::MessageParser<GetAllSubmodelReferencesRpcResponse>(() => new GetAllSubmodelReferencesRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllSubmodelReferencesRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelReferencesRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelReferencesRpcResponse(GetAllSubmodelReferencesRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      pagingMetaData_ = other.pagingMetaData_ != null ? other.pagingMetaData_.Clone() : null;
      payload_ = other.payload_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllSubmodelReferencesRpcResponse Clone() {
      return new GetAllSubmodelReferencesRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "pagingMetaData" field.</summary>
    public const int PagingMetaDataFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.Services.PagedResultPagingMetadata pagingMetaData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.Services.PagedResultPagingMetadata PagingMetaData {
      get { return pagingMetaData_; }
      set {
        pagingMetaData_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private static readonly pb::FieldCodec<global::FSR.GRPC.Lib.V3.ReferenceDTO> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(26, global::FSR.GRPC.Lib.V3.ReferenceDTO.Parser);
    private readonly pbc::RepeatedField<global::FSR.GRPC.Lib.V3.ReferenceDTO> payload_ = new pbc::RepeatedField<global::FSR.GRPC.Lib.V3.ReferenceDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FSR.GRPC.Lib.V3.ReferenceDTO> Payload {
      get { return payload_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllSubmodelReferencesRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllSubmodelReferencesRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(PagingMetaData, other.PagingMetaData)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (pagingMetaData_ != null) hash ^= PagingMetaData.GetHashCode();
      hash ^= payload_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (pagingMetaData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PagingMetaData);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (pagingMetaData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PagingMetaData);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllSubmodelReferencesRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.pagingMetaData_ != null) {
        if (pagingMetaData_ == null) {
          PagingMetaData = new global::FSR.GRPC.Lib.V3.Services.PagedResultPagingMetadata();
        }
        PagingMetaData.MergeFrom(other.PagingMetaData);
      }
      payload_.Add(other.payload_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (pagingMetaData_ == null) {
              PagingMetaData = new global::FSR.GRPC.Lib.V3.Services.PagedResultPagingMetadata();
            }
            input.ReadMessage(PagingMetaData);
            break;
          }
          case 26: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostSubmodelReferenceRpcRequest : pb::IMessage<PostSubmodelReferenceRpcRequest> {
    private static readonly pb::MessageParser<PostSubmodelReferenceRpcRequest> _parser = new pb::MessageParser<PostSubmodelReferenceRpcRequest>(() => new PostSubmodelReferenceRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostSubmodelReferenceRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelReferenceRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelReferenceRpcRequest(PostSubmodelReferenceRpcRequest other) : this() {
      id_ = other.id_;
      submodelRef_ = other.submodelRef_ != null ? other.submodelRef_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelReferenceRpcRequest Clone() {
      return new PostSubmodelReferenceRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "submodelRef" field.</summary>
    public const int SubmodelRefFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.ReferenceDTO submodelRef_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.ReferenceDTO SubmodelRef {
      get { return submodelRef_; }
      set {
        submodelRef_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostSubmodelReferenceRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostSubmodelReferenceRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(SubmodelRef, other.SubmodelRef)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (submodelRef_ != null) hash ^= SubmodelRef.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (submodelRef_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SubmodelRef);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (submodelRef_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SubmodelRef);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostSubmodelReferenceRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.submodelRef_ != null) {
        if (submodelRef_ == null) {
          SubmodelRef = new global::FSR.GRPC.Lib.V3.ReferenceDTO();
        }
        SubmodelRef.MergeFrom(other.SubmodelRef);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (submodelRef_ == null) {
              SubmodelRef = new global::FSR.GRPC.Lib.V3.ReferenceDTO();
            }
            input.ReadMessage(SubmodelRef);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PostSubmodelReferenceRpcResponse : pb::IMessage<PostSubmodelReferenceRpcResponse> {
    private static readonly pb::MessageParser<PostSubmodelReferenceRpcResponse> _parser = new pb::MessageParser<PostSubmodelReferenceRpcResponse>(() => new PostSubmodelReferenceRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PostSubmodelReferenceRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelReferenceRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelReferenceRpcResponse(PostSubmodelReferenceRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      submodelRef_ = other.submodelRef_ != null ? other.submodelRef_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PostSubmodelReferenceRpcResponse Clone() {
      return new PostSubmodelReferenceRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "submodelRef" field.</summary>
    public const int SubmodelRefFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.ReferenceDTO submodelRef_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.ReferenceDTO SubmodelRef {
      get { return submodelRef_; }
      set {
        submodelRef_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PostSubmodelReferenceRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PostSubmodelReferenceRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(SubmodelRef, other.SubmodelRef)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (submodelRef_ != null) hash ^= SubmodelRef.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (submodelRef_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SubmodelRef);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (submodelRef_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SubmodelRef);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PostSubmodelReferenceRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.submodelRef_ != null) {
        if (submodelRef_ == null) {
          SubmodelRef = new global::FSR.GRPC.Lib.V3.ReferenceDTO();
        }
        SubmodelRef.MergeFrom(other.SubmodelRef);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (submodelRef_ == null) {
              SubmodelRef = new global::FSR.GRPC.Lib.V3.ReferenceDTO();
            }
            input.ReadMessage(SubmodelRef);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteSubmodelReferenceRpcRequest : pb::IMessage<DeleteSubmodelReferenceRpcRequest> {
    private static readonly pb::MessageParser<DeleteSubmodelReferenceRpcRequest> _parser = new pb::MessageParser<DeleteSubmodelReferenceRpcRequest>(() => new DeleteSubmodelReferenceRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteSubmodelReferenceRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelReferenceRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelReferenceRpcRequest(DeleteSubmodelReferenceRpcRequest other) : this() {
      id_ = other.id_;
      submodelId_ = other.submodelId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelReferenceRpcRequest Clone() {
      return new DeleteSubmodelReferenceRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "submodelId" field.</summary>
    public const int SubmodelIdFieldNumber = 2;
    private string submodelId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SubmodelId {
      get { return submodelId_; }
      set {
        submodelId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteSubmodelReferenceRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteSubmodelReferenceRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (SubmodelId != other.SubmodelId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (SubmodelId.Length != 0) hash ^= SubmodelId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (SubmodelId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SubmodelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (SubmodelId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubmodelId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteSubmodelReferenceRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.SubmodelId.Length != 0) {
        SubmodelId = other.SubmodelId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            SubmodelId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DeleteSubmodelReferenceRpcResponse : pb::IMessage<DeleteSubmodelReferenceRpcResponse> {
    private static readonly pb::MessageParser<DeleteSubmodelReferenceRpcResponse> _parser = new pb::MessageParser<DeleteSubmodelReferenceRpcResponse>(() => new DeleteSubmodelReferenceRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeleteSubmodelReferenceRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelReferenceRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelReferenceRpcResponse(DeleteSubmodelReferenceRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeleteSubmodelReferenceRpcResponse Clone() {
      return new DeleteSubmodelReferenceRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeleteSubmodelReferenceRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeleteSubmodelReferenceRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeleteSubmodelReferenceRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAssetInformationRpcRequest : pb::IMessage<GetAssetInformationRpcRequest> {
    private static readonly pb::MessageParser<GetAssetInformationRpcRequest> _parser = new pb::MessageParser<GetAssetInformationRpcRequest>(() => new GetAssetInformationRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAssetInformationRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetInformationRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetInformationRpcRequest(GetAssetInformationRpcRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetInformationRpcRequest Clone() {
      return new GetAssetInformationRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAssetInformationRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAssetInformationRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAssetInformationRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAssetInformationRpcResponse : pb::IMessage<GetAssetInformationRpcResponse> {
    private static readonly pb::MessageParser<GetAssetInformationRpcResponse> _parser = new pb::MessageParser<GetAssetInformationRpcResponse>(() => new GetAssetInformationRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAssetInformationRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetInformationRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetInformationRpcResponse(GetAssetInformationRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      assetInformation_ = other.assetInformation_ != null ? other.assetInformation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetInformationRpcResponse Clone() {
      return new GetAssetInformationRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "assetInformation" field.</summary>
    public const int AssetInformationFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.AssetInformationDTO assetInformation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.AssetInformationDTO AssetInformation {
      get { return assetInformation_; }
      set {
        assetInformation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAssetInformationRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAssetInformationRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(AssetInformation, other.AssetInformation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (assetInformation_ != null) hash ^= AssetInformation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (assetInformation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AssetInformation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (assetInformation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AssetInformation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAssetInformationRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.assetInformation_ != null) {
        if (assetInformation_ == null) {
          AssetInformation = new global::FSR.GRPC.Lib.V3.AssetInformationDTO();
        }
        AssetInformation.MergeFrom(other.AssetInformation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (assetInformation_ == null) {
              AssetInformation = new global::FSR.GRPC.Lib.V3.AssetInformationDTO();
            }
            input.ReadMessage(AssetInformation);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutAssetInformationRpcRequest : pb::IMessage<PutAssetInformationRpcRequest> {
    private static readonly pb::MessageParser<PutAssetInformationRpcRequest> _parser = new pb::MessageParser<PutAssetInformationRpcRequest>(() => new PutAssetInformationRpcRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutAssetInformationRpcRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetInformationRpcRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetInformationRpcRequest(PutAssetInformationRpcRequest other) : this() {
      id_ = other.id_;
      assetInformation_ = other.assetInformation_ != null ? other.assetInformation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetInformationRpcRequest Clone() {
      return new PutAssetInformationRpcRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "assetInformation" field.</summary>
    public const int AssetInformationFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.AssetInformationDTO assetInformation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.AssetInformationDTO AssetInformation {
      get { return assetInformation_; }
      set {
        assetInformation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutAssetInformationRpcRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutAssetInformationRpcRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(AssetInformation, other.AssetInformation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (assetInformation_ != null) hash ^= AssetInformation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (assetInformation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AssetInformation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (assetInformation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AssetInformation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutAssetInformationRpcRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.assetInformation_ != null) {
        if (assetInformation_ == null) {
          AssetInformation = new global::FSR.GRPC.Lib.V3.AssetInformationDTO();
        }
        AssetInformation.MergeFrom(other.AssetInformation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            if (assetInformation_ == null) {
              AssetInformation = new global::FSR.GRPC.Lib.V3.AssetInformationDTO();
            }
            input.ReadMessage(AssetInformation);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutAssetInformationRpcResponse : pb::IMessage<PutAssetInformationRpcResponse> {
    private static readonly pb::MessageParser<PutAssetInformationRpcResponse> _parser = new pb::MessageParser<PutAssetInformationRpcResponse>(() => new PutAssetInformationRpcResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutAssetInformationRpcResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FSR.GRPC.Lib.V3.Services.AssetAdministrationShellService.AssetAdministrationShellServiceReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetInformationRpcResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetInformationRpcResponse(PutAssetInformationRpcResponse other) : this() {
      statusCode_ = other.statusCode_;
      assetInformation_ = other.assetInformation_ != null ? other.assetInformation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutAssetInformationRpcResponse Clone() {
      return new PutAssetInformationRpcResponse(this);
    }

    /// <summary>Field number for the "statusCode" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "assetInformation" field.</summary>
    public const int AssetInformationFieldNumber = 2;
    private global::FSR.GRPC.Lib.V3.AssetInformationDTO assetInformation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FSR.GRPC.Lib.V3.AssetInformationDTO AssetInformation {
      get { return assetInformation_; }
      set {
        assetInformation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutAssetInformationRpcResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutAssetInformationRpcResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (!object.Equals(AssetInformation, other.AssetInformation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (assetInformation_ != null) hash ^= AssetInformation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (assetInformation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AssetInformation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (assetInformation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AssetInformation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutAssetInformationRpcResponse other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.assetInformation_ != null) {
        if (assetInformation_ == null) {
          AssetInformation = new global::FSR.GRPC.Lib.V3.AssetInformationDTO();
        }
        AssetInformation.MergeFrom(other.AssetInformation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            if (assetInformation_ == null) {
              AssetInformation = new global::FSR.GRPC.Lib.V3.AssetInformationDTO();
            }
            input.ReadMessage(AssetInformation);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
