# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from Protos.Services import SubmodelService_pb2 as Protos_dot_Services_dot_SubmodelService__pb2


class SubmodelServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSubmodel = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/GetSubmodel',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelRpcResponse.FromString,
        )
    self.GetAllSubmodelElements = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/GetAllSubmodelElements',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetAllSubmodelElementsRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetAllSubmodelElementsRpcResponse.FromString,
        )
    self.GetSubmodelElementByPath = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/GetSubmodelElementByPath',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelElementByPathRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelElementByPathRpcResponse.FromString,
        )
    self.PutSubmodel = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/PutSubmodel',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelRpcResponse.FromString,
        )
    self.PostSubmodelElement = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/PostSubmodelElement',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementRpcResponse.FromString,
        )
    self.PostSubmodelElementByPath = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/PostSubmodelElementByPath',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementByPathRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementByPathRpcResponse.FromString,
        )
    self.PutSubmodelElementByPath = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/PutSubmodelElementByPath',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelElementByPathRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelElementByPathRpcResponse.FromString,
        )
    self.SetSubmodelElementValueByPath = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/SetSubmodelElementValueByPath',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.SetSubmodelElementValueByPathRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.SetSubmodelElementValueByPathRpcResponse.FromString,
        )
    self.DeleteSubmodelElementByPath = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/DeleteSubmodelElementByPath',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.DeleteSubmodelElementByPathRpcRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.DeleteSubmodelElementByPathRpcResponse.FromString,
        )
    self.InvokeOperationSync = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/InvokeOperationSync',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationSyncRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationSyncResponse.FromString,
        )
    self.InvokeOperationAsync = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/InvokeOperationAsync',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationAsyncRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationAsyncResponse.FromString,
        )
    self.GetOperationAsyncResult = channel.unary_unary(
        '/FSR.Aas.GRPC.Lib.V3.SubmodelService/GetOperationAsyncResult',
        request_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetOperationAsyncResultRequest.SerializeToString,
        response_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetOperationAsyncResultResponse.FromString,
        )


class SubmodelServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSubmodel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllSubmodelElements(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSubmodelElementByPath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutSubmodel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostSubmodelElement(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostSubmodelElementByPath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PutSubmodelElementByPath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetSubmodelElementValueByPath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSubmodelElementByPath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InvokeOperationSync(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InvokeOperationAsync(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOperationAsyncResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SubmodelServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSubmodel': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubmodel,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelRpcResponse.SerializeToString,
      ),
      'GetAllSubmodelElements': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllSubmodelElements,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetAllSubmodelElementsRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetAllSubmodelElementsRpcResponse.SerializeToString,
      ),
      'GetSubmodelElementByPath': grpc.unary_unary_rpc_method_handler(
          servicer.GetSubmodelElementByPath,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelElementByPathRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetSubmodelElementByPathRpcResponse.SerializeToString,
      ),
      'PutSubmodel': grpc.unary_unary_rpc_method_handler(
          servicer.PutSubmodel,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelRpcResponse.SerializeToString,
      ),
      'PostSubmodelElement': grpc.unary_unary_rpc_method_handler(
          servicer.PostSubmodelElement,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementRpcResponse.SerializeToString,
      ),
      'PostSubmodelElementByPath': grpc.unary_unary_rpc_method_handler(
          servicer.PostSubmodelElementByPath,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementByPathRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PostSubmodelElementByPathRpcResponse.SerializeToString,
      ),
      'PutSubmodelElementByPath': grpc.unary_unary_rpc_method_handler(
          servicer.PutSubmodelElementByPath,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelElementByPathRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.PutSubmodelElementByPathRpcResponse.SerializeToString,
      ),
      'SetSubmodelElementValueByPath': grpc.unary_unary_rpc_method_handler(
          servicer.SetSubmodelElementValueByPath,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.SetSubmodelElementValueByPathRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.SetSubmodelElementValueByPathRpcResponse.SerializeToString,
      ),
      'DeleteSubmodelElementByPath': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSubmodelElementByPath,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.DeleteSubmodelElementByPathRpcRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.DeleteSubmodelElementByPathRpcResponse.SerializeToString,
      ),
      'InvokeOperationSync': grpc.unary_unary_rpc_method_handler(
          servicer.InvokeOperationSync,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationSyncRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationSyncResponse.SerializeToString,
      ),
      'InvokeOperationAsync': grpc.unary_unary_rpc_method_handler(
          servicer.InvokeOperationAsync,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationAsyncRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.InvokeOperationAsyncResponse.SerializeToString,
      ),
      'GetOperationAsyncResult': grpc.unary_unary_rpc_method_handler(
          servicer.GetOperationAsyncResult,
          request_deserializer=Protos_dot_Services_dot_SubmodelService__pb2.GetOperationAsyncResultRequest.FromString,
          response_serializer=Protos_dot_Services_dot_SubmodelService__pb2.GetOperationAsyncResultResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FSR.Aas.GRPC.Lib.V3.SubmodelService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
